
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.event.ChangeEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Emanuel
 */
public class ConversorDeTiempo extends javax.swing.JFrame {

    /**
     * Creates new form ConversorDeTiempo
     */
    public ConversorDeTiempo() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rsscalelabel.RSScaleLabel.setScaleLabel(LabelTiempo, "src/Imagenes/Relogplata.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(LabelCarreteraVerde, "src/Imagenes/Carreteraverde.jpg");
        
    }

    //METODO PARA AÑADIR IMAGENES
    public void SetImageLabel(JLabel labelname, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icono = new ImageIcon(
                image.getImage().getScaledInstance(
                        labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new JPanelGradientGris();
        Minutos = new javax.swing.JTextField();
        Semanas = new javax.swing.JTextField();
        Meses = new javax.swing.JTextField();
        Dias = new javax.swing.JTextField();
        IntroducirHoras = new javax.swing.JTextField();
        LabelTiempo = new javax.swing.JLabel();
        LabelCarreteraVerde = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(426, 456));
        setPreferredSize(new java.awt.Dimension(379, 377));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(380, 456));
        jPanel1.setPreferredSize(new java.awt.Dimension(390, 456));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Minutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinutosActionPerformed(evt);
            }
        });
        jPanel1.add(Minutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, -1));
        jPanel1.add(Semanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 90, -1));

        Meses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesesActionPerformed(evt);
            }
        });
        jPanel1.add(Meses, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 90, -1));

        Dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiasActionPerformed(evt);
            }
        });
        Dias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DiasKeyReleased(evt);
            }
        });
        jPanel1.add(Dias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 90, -1));

        IntroducirHoras.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                IntroducirHorasComponentAdded(evt);
            }
        });
        IntroducirHoras.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                IntroducirHorasCaretUpdate(evt);
            }
        });
        IntroducirHoras.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                IntroducirHorasHierarchyChanged(evt);
            }
        });
        IntroducirHoras.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                IntroducirHorasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        IntroducirHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntroducirHorasActionPerformed(evt);
            }
        });
        IntroducirHoras.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                IntroducirHorasPropertyChange(evt);
            }
        });
        IntroducirHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IntroducirHorasKeyReleased(evt);
            }
        });
        IntroducirHoras.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                IntroducirHorasVetoableChange(evt);
            }
        });
        jPanel1.add(IntroducirHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, -1));
        jPanel1.add(LabelTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 170, 120));
        jPanel1.add(LabelCarreteraVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 380, 200));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Meses");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 60, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Minutos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Horas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dias");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 60, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Semanas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (Menus.conversoresTiempo == 1) {
            Menus.conversoresTiempo--;

        } else {
        }
    }//GEN-LAST:event_formWindowClosing

    private void DiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiasActionPerformed
          // TODO add your handling code here:
          
          
    }//GEN-LAST:event_DiasActionPerformed

    private void MinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinutosActionPerformed

    private void MesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MesesActionPerformed

    private void IntroducirHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntroducirHorasActionPerformed
        
    }//GEN-LAST:event_IntroducirHorasActionPerformed

    
    private void IntroducirHorasVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_IntroducirHorasVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_IntroducirHorasVetoableChange

    private void IntroducirHorasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_IntroducirHorasAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_IntroducirHorasAncestorAdded

    private void IntroducirHorasCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_IntroducirHorasCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_IntroducirHorasCaretUpdate

    private void IntroducirHorasComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_IntroducirHorasComponentAdded
      // TODO add your handling code here:
    }//GEN-LAST:event_IntroducirHorasComponentAdded

    private void IntroducirHorasHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_IntroducirHorasHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_IntroducirHorasHierarchyChanged

    private void IntroducirHorasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_IntroducirHorasPropertyChange
           // TODO add your handling code here:
    }//GEN-LAST:event_IntroducirHorasPropertyChange

    private void IntroducirHorasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IntroducirHorasKeyReleased
/* String horas = IntroducirHoras.getText();
       IntroducirHoras.setDocument(new LimitedTextField(7));
        if (horas.matches("^[0-9]+$")) {
            
        
        int horasconversas = Integer.parseInt( horas);
        int minutos = horasconversas * 60;
        int dias = horasconversas / 24;
        int semanas = dias / 7;
        int meses = semanas / 4;
        String horasString = Integer.toString(horasconversas);
       String minutosString=  Integer.toString(minutos);
       String diasString=  Integer.toString(dias);
       String mesesString=   Integer.toString(meses);
       String semanasString= Integer.toString(semanas);
       
       IntroducirHoras.setText(horasString);
       Minutos.setText(minutosString);
       Dias.setText(diasString);
      Semanas.setText(semanasString);
       Meses.setText(mesesString);}        // TODO add your handling code here:
      */
    }//GEN-LAST:event_IntroducirHorasKeyReleased

    private void DiasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DiasKeyReleased
         // TODO add your handling code here:
          String dias = Dias.getText();
       Dias.setDocument(new LimitedTextField(7));
        if (dias.matches("^[0-9]+$")) {
            
        
        int diasInt = Integer.parseInt( dias);
        
        int horas = diasInt * 24;
        int minutos = horas * 60;
        int semanas = diasInt / 7;
        int meses = semanas / 4;
        String horasString = Integer.toString(horas);
       String minutosString=  Integer.toString(minutos);
       String diasString=  Integer.toString(diasInt);
       String mesesString=   Integer.toString(meses);
       String semanasString= Integer.toString(semanas);
       
       IntroducirHoras.setText(horasString);
       Minutos.setText(minutosString);
       Dias.setText(diasString);
      Semanas.setText(semanasString);
       Meses.setText(mesesString);}
    }//GEN-LAST:event_DiasKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTiempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTiempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTiempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTiempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorDeTiempo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dias;
    private javax.swing.JTextField IntroducirHoras;
    private javax.swing.JLabel LabelCarreteraVerde;
    private javax.swing.JLabel LabelTiempo;
    private javax.swing.JTextField Meses;
    private javax.swing.JTextField Minutos;
    private javax.swing.JTextField Semanas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
